### ISSUE TITLE
stream.stream() does not advance the stream

### ISSUE THREAD

**Issue by watson** [mafintosh/mp4-stream#13]
According to the docs, calling `stream.stream()` should advance the stream so that the `box` event fires again if there are more boxes. This does not happen.

Below is the code I would expect to work, but it only ever emits the first box. I've validated that the stream returned from `stream.stream()` does emit an `end` event, so that's not the issue. Also, it does call the `_kick` function, but the problem is that `_pending` isn't `0`. I just can't figure out why - could be an off-by-one error.

``` js
var fs = require('fs')
var mp4 = require('mp4-stream')

var stream = mp4.decode()

stream.on('box', function (headers) {
  console.log(headers.type)
  stream.stream().resume()
})

fs.createReadStream('./test.m4v').pipe(stream)
```

**Comment by nklhrstv** [comment]
I have similar issue.
