### ISSUE TITLE
The Sample Size Atoms (stsz) are incorrectly parsed

### ISSUE THREAD

**Issue by fpinzn** [mafintosh/mp4-stream#4]
The sample size atom structure differs slightly from the others, as it has an extra 4 bytes after the `version` and `flags` to store the `sample size` in case its the same for all the samples.

If not, the the `sample size` entry is set to 0 and the sample size table is used instead. Said table contains an an entry for each sample in the media's data stream.

[Source](https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-BBCBBCGB)

Because of this error, the parser returns as if the sample size table has no entries.

**Comment by mafintosh** [comment]
I think @jhiesey recently fixed a lot of outstanding issues. Can you try 2.0.0 and see if this is still broken?

**Comment by fpinzn** [comment]
Its fixed now. Great work @jhiesey!
